// <auto-generated />
using System;
using DatabaseContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseContext.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20210307153029_MigrationModel_003")]
    partial class MigrationModel_003
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainModels.General.Branch", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("ParentId");

                    b.ToTable("Branchs","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41c33ac0-dae6-4a02-ba29-be74c6e9f98f"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 177, DateTimeKind.Local).AddTicks(1040),
                            Title = "Main"
                        });
                });

            modelBuilder.Entity("DomainModels.General.BranchRole", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("BranchId");

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("RoleId");

                    b.ToTable("BranchRoles","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c01fe8f6-41c7-4440-86bb-50816ebc2838"),
                            BranchId = new Guid("41c33ac0-dae6-4a02-ba29-be74c6e9f98f"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 177, DateTimeKind.Local).AddTicks(1755),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        });
                });

            modelBuilder.Entity("DomainModels.General.BranchRoleMember", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("BranchRoleId");

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("MemberId");

                    b.ToTable("BranchRoleMembers","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("248013bb-7a27-48ba-9e44-a406dda638b9"),
                            BranchRoleId = new Guid("c01fe8f6-41c7-4440-86bb-50816ebc2838"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 178, DateTimeKind.Local).AddTicks(7721),
                            MemberId = new Guid("8a5e037d-9c1d-46eb-9002-fca33d446e37")
                        });
                });

            modelBuilder.Entity("DomainModels.General.Log", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("State")
                        .HasColumnType("tinyint")
                        .HasMaxLength(10);

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("MemberId");

                    b.ToTable("Logs","General");
                });

            modelBuilder.Entity("DomainModels.General.LogDetail", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid?>("LogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("LogId");

                    b.ToTable("LogDetails","General");
                });

            modelBuilder.Entity("DomainModels.General.Member", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PersonId");

                    b.ToTable("Members","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a5e037d-9c1d-46eb-9002-fca33d446e37"),
                            Active = true,
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 176, DateTimeKind.Local).AddTicks(7913),
                            Password = "10921321718522810424013620812023319215824350233",
                            PersonId = new Guid("a98ee288-942e-4f39-bfe7-81765d4dbceb"),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DomainModels.General.Permission", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("ParentId");

                    b.ToTable("Permissions","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Action = "",
                            Active = true,
                            Controller = "",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 660, DateTimeKind.Unspecified).AddTicks(7050),
                            Icon = "fa fa-address-book",
                            Order = 1,
                            Title = "اطلاعات پایه",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("e6ebe0b5-601a-4fcc-adba-0e30d861c2f4"),
                            Action = "",
                            Active = true,
                            Controller = "",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(1038),
                            Icon = "fa fa-server",
                            Order = 2,
                            Title = "سیستم",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Action = "Index",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(1250),
                            Icon = "fa fa-users",
                            Order = 1,
                            ParentId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Title = "تعریف نقش",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Action = "Index",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(1335),
                            Icon = "fa fa-user",
                            Order = 2,
                            ParentId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Title = "تعریف کاربر",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Action = "Index",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2258),
                            Icon = "fa fa-cogs",
                            Order = 3,
                            ParentId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Title = "سطح دسترسی",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("e7c93552-4e07-4d69-ba6a-baa5229c2278"),
                            Action = "_Create",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2389),
                            Icon = "fa fa-plus",
                            Order = 4,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "ثبت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("67323792-38c3-490b-ba31-eb87c1087ea6"),
                            Action = "_Update",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2464),
                            Icon = "fa fa-edit",
                            Order = 3,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "ویرایش",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("0c19f3a5-a90c-4760-968d-af6028fef21f"),
                            Action = "_Delete",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2547),
                            Icon = "fa fa-trash",
                            Order = 1,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "حذف",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("547e86be-132e-41f7-a8f3-73eb25bd755b"),
                            Action = "_List",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2625),
                            Icon = "fa fa-list",
                            Order = 2,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "اطلاعات",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("3a4b0912-7700-41cd-84ca-9986a6af982a"),
                            Action = "_Menu",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2700),
                            Icon = "fa fa-navicon",
                            Order = 1,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "منو",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("a05ecc96-0663-4fb2-aabd-18dede5a5cff"),
                            Action = "_Create",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2772),
                            Icon = "fa fa-plus",
                            Order = 2,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "ثبت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("ff298292-be77-43a0-ac99-d31f6c38c0bb"),
                            Action = "_Role",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2842),
                            Icon = "fa fa-users",
                            Order = 8,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "گروه کاربری",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("0da690bc-f675-4d8f-82f5-e6d4a5f82918"),
                            Action = "_Order",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2912),
                            Icon = "fa fa-list-ol",
                            Order = 6,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "اولویت بندی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("8c4994a2-a808-4c81-8086-ee501b2ac0fe"),
                            Action = "_Member",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2987),
                            Icon = "fa fa-user",
                            Order = 7,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "کاربر",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("9e404679-1059-495e-aaec-9aa9371ed354"),
                            Action = "_Update",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3057),
                            Icon = "fa fa-edit",
                            Order = 4,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "ویرایش",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("b41312d1-cec1-4f3b-935f-5359bba15936"),
                            Action = "_List",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3177),
                            Icon = "fa fa-list",
                            Order = 5,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "اطلاعات",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("b9a02ea5-dd3f-48a8-831b-5f4154544f00"),
                            Action = "_Delete",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3256),
                            Icon = "fa fa-trash",
                            Order = 3,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "حذف",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("cb313af5-85ba-42b0-a263-6ae1549dc13b"),
                            Action = "ChangePeriority",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3332),
                            Icon = "fa fa-edit",
                            Order = 1,
                            ParentId = new Guid("0da690bc-f675-4d8f-82f5-e6d4a5f82918"),
                            Title = "تغییر اولویت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("0b56bebc-01ff-4619-bd45-4652fecef76e"),
                            Action = "SetRolePermission",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3404),
                            Icon = "fa fa-edit",
                            Order = 1,
                            ParentId = new Guid("ff298292-be77-43a0-ac99-d31f6c38c0bb"),
                            Title = "تخصیص دسترسی گروه",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("3c3f40b8-7399-41d5-a5ce-00c6e0ffb583"),
                            Action = "SetMemberPermission",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3475),
                            Icon = "fa fa-edit",
                            Order = 1,
                            ParentId = new Guid("8c4994a2-a808-4c81-8086-ee501b2ac0fe"),
                            Title = "تخصیص دسترسی کاربر",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("9009f178-1385-4fed-b0a7-abd5aee7a521"),
                            Action = "_Tree",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3547),
                            Icon = "fa fa-list-ul",
                            Order = 6,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "نمایش درختی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("d49cdafd-e0ae-46c1-ba80-d4a9b71f86a6"),
                            Action = "_Create",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3620),
                            Icon = "fa fa-plus",
                            Order = 1,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "ثبت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("15c526e5-879a-4a4a-84fb-06941ec9e78e"),
                            Action = "_Update",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3692),
                            Icon = "fa fa-edit",
                            Order = 2,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "ویرایش",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("07760487-9097-4431-b7b9-b6dbf9bd9416"),
                            Action = "_List",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3764),
                            Icon = "fa fa-list",
                            Order = 4,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "اطلاعات",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("643eef28-7e01-40d8-bfe7-4cd5c95c770e"),
                            Action = "_Delete",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3836),
                            Icon = "fa fa-trash",
                            Order = 3,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "حذف",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("4a6668fe-92ce-47e9-ac44-73312d71a602"),
                            Action = "_Permission",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3907),
                            Icon = "fa fa-cogs",
                            Order = 7,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "دسترسی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("44683454-d0a3-48ee-bc83-fa18f6103e65"),
                            Action = "_Permission",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(4022),
                            Icon = "fa fa-cogs",
                            Order = 5,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "دسترسی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("fc5a8eae-9287-4efc-91de-9d1c47e19aa6"),
                            Action = "_Tree",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 2, 4, 22, 25, 6, 390, DateTimeKind.Unspecified),
                            Icon = "fa fa-list-ul",
                            Order = 10,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "نمایش درختی",
                            Visible = false
                        });
                });

            modelBuilder.Entity("DomainModels.General.Person", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Persons","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a98ee288-942e-4f39-bfe7-81765d4dbceb"),
                            Birthday = new DateTime(1993, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 172, DateTimeKind.Local).AddTicks(9611),
                            Email = "Vahid031@yahoo.com",
                            FirstName = "وحید",
                            Gender = true,
                            LastName = "گودرزی",
                            MobileNumber = "09212681463",
                            NationalCode = "0310956196",
                            PhoneNumber = "02634558363"
                        });
                });

            modelBuilder.Entity("DomainModels.General.Role", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("ParentId");

                    b.ToTable("Roles","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 177, DateTimeKind.Local).AddTicks(322),
                            Title = "Admin"
                        });
                });

            modelBuilder.Entity("DomainModels.General.RolePermission", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3314925a-2866-4dcf-b0ea-afd75a1e20a9"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(2203),
                            PermissionId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("8369172c-97b2-4e2e-a144-a24830ac7d04"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3503),
                            PermissionId = new Guid("e6ebe0b5-601a-4fcc-adba-0e30d861c2f4"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("e292a827-6c8e-4cd6-9ad8-607f8c532a94"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3575),
                            PermissionId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("7f33f3a9-d825-469d-857b-d6e37dc76f7a"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3602),
                            PermissionId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("5510f93f-c8ad-4740-968e-7ee9c059c11c"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3637),
                            PermissionId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("2b18e304-c1e2-4cf8-baf8-e90c4ed08a30"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3664),
                            PermissionId = new Guid("e7c93552-4e07-4d69-ba6a-baa5229c2278"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("d9b3f429-74bd-40c8-90fd-a652ed4f2025"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3688),
                            PermissionId = new Guid("67323792-38c3-490b-ba31-eb87c1087ea6"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("b0fae8ec-efe3-4ffd-bd16-69c14af4efcf"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3712),
                            PermissionId = new Guid("0c19f3a5-a90c-4760-968d-af6028fef21f"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("9aaeee6c-b9ef-425c-b3d2-2207226ed917"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3735),
                            PermissionId = new Guid("547e86be-132e-41f7-a8f3-73eb25bd755b"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("6932d95a-bfba-4262-a35c-62be61026c83"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3760),
                            PermissionId = new Guid("3a4b0912-7700-41cd-84ca-9986a6af982a"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("a154b6ed-80ff-434a-9f71-44fb867293a6"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3783),
                            PermissionId = new Guid("a05ecc96-0663-4fb2-aabd-18dede5a5cff"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("3351f8a6-fe9d-4b68-999a-6faa9e79fbcd"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3806),
                            PermissionId = new Guid("ff298292-be77-43a0-ac99-d31f6c38c0bb"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("6dca39aa-434a-4312-9acb-387ac788e42d"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3833),
                            PermissionId = new Guid("0da690bc-f675-4d8f-82f5-e6d4a5f82918"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("88e05075-8dd6-40c3-a883-93c1bfe4381d"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3856),
                            PermissionId = new Guid("8c4994a2-a808-4c81-8086-ee501b2ac0fe"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("e2f06773-2164-46e4-b286-b3ab87249477"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3879),
                            PermissionId = new Guid("9e404679-1059-495e-aaec-9aa9371ed354"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("c505278a-0a2f-4eac-ae51-e7fc3e7b1b9b"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3902),
                            PermissionId = new Guid("b41312d1-cec1-4f3b-935f-5359bba15936"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("3903a518-c1ba-4a8e-a2fb-f59baa220d45"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3924),
                            PermissionId = new Guid("b9a02ea5-dd3f-48a8-831b-5f4154544f00"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("4c0e9270-5d1c-4e61-b2eb-d36e1dee9008"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3949),
                            PermissionId = new Guid("cb313af5-85ba-42b0-a263-6ae1549dc13b"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("162a9fe7-8fbd-4759-8025-cfc2f0eea7b7"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3972),
                            PermissionId = new Guid("0b56bebc-01ff-4619-bd45-4652fecef76e"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("adddc242-d853-4d3e-938b-965aed02e3e7"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(3995),
                            PermissionId = new Guid("3c3f40b8-7399-41d5-a5ce-00c6e0ffb583"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("9293c3eb-207e-4b78-8fed-6d3b96437302"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(4020),
                            PermissionId = new Guid("9009f178-1385-4fed-b0a7-abd5aee7a521"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("4f13f41d-b67f-4bde-a183-f9ede4bb69b0"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(4139),
                            PermissionId = new Guid("d49cdafd-e0ae-46c1-ba80-d4a9b71f86a6"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("ce8d0ceb-d62b-437f-a805-ff02cc1e167c"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(4164),
                            PermissionId = new Guid("15c526e5-879a-4a4a-84fb-06941ec9e78e"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("40a3634b-5a40-4004-9582-a1f577f1a768"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(4187),
                            PermissionId = new Guid("07760487-9097-4431-b7b9-b6dbf9bd9416"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("4e9e87f2-033c-4b1c-bbf5-a5e1852727a5"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(4211),
                            PermissionId = new Guid("643eef28-7e01-40d8-bfe7-4cd5c95c770e"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("177bdb67-5947-4019-8912-f19d90204c0e"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(4235),
                            PermissionId = new Guid("4a6668fe-92ce-47e9-ac44-73312d71a602"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("28f037fc-616d-4ac5-8804-091d62a2b5e1"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(4259),
                            PermissionId = new Guid("44683454-d0a3-48ee-bc83-fa18f6103e65"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        },
                        new
                        {
                            Id = new Guid("6fbebd58-1813-4f37-aba9-d58958f1628f"),
                            CreateDate = new DateTime(2021, 3, 7, 19, 0, 29, 279, DateTimeKind.Local).AddTicks(4282),
                            PermissionId = new Guid("fc5a8eae-9287-4efc-91de-9d1c47e19aa6"),
                            RoleId = new Guid("81bd3e58-8d58-4757-adec-90610ad04fef")
                        });
                });

            modelBuilder.Entity("DomainModels.General.Branch", b =>
                {
                    b.HasOne("DomainModels.General.Branch", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("DomainModels.General.BranchRole", b =>
                {
                    b.HasOne("DomainModels.General.Branch", "Branch")
                        .WithMany("BranchRoles")
                        .HasForeignKey("BranchId");

                    b.HasOne("DomainModels.General.Role", "Role")
                        .WithMany("BranchRoles")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("DomainModels.General.BranchRoleMember", b =>
                {
                    b.HasOne("DomainModels.General.BranchRole", "BranchRole")
                        .WithMany()
                        .HasForeignKey("BranchRoleId");

                    b.HasOne("DomainModels.General.Member", "Member")
                        .WithMany("BranchRoleMembers")
                        .HasForeignKey("MemberId");
                });

            modelBuilder.Entity("DomainModels.General.Log", b =>
                {
                    b.HasOne("DomainModels.General.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");
                });

            modelBuilder.Entity("DomainModels.General.LogDetail", b =>
                {
                    b.HasOne("DomainModels.General.Log", "Log")
                        .WithMany("LogDetails")
                        .HasForeignKey("LogId");
                });

            modelBuilder.Entity("DomainModels.General.Member", b =>
                {
                    b.HasOne("DomainModels.General.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("DomainModels.General.Permission", b =>
                {
                    b.HasOne("DomainModels.General.Permission", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("DomainModels.General.Role", b =>
                {
                    b.HasOne("DomainModels.General.Role", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("DomainModels.General.RolePermission", b =>
                {
                    b.HasOne("DomainModels.General.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId");

                    b.HasOne("DomainModels.General.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
