// <auto-generated />
using System;
using DatabaseContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseContext.Migrations
{
    [DbContext(typeof(UnitOfWork))]
    [Migration("20210129192849_MigrationModel_002")]
    partial class MigrationModel_002
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainModels.General.Log", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("State")
                        .HasColumnType("tinyint")
                        .HasMaxLength(10);

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("MemberId");

                    b.ToTable("Logs","General");
                });

            modelBuilder.Entity("DomainModels.General.LogDetail", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyName")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("PropertyValue")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("LogId");

                    b.ToTable("LogDetails","General");
                });

            modelBuilder.Entity("DomainModels.General.Member", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PersonId");

                    b.ToTable("Members","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4c1b92e9-d68b-4794-8f0f-293b67eed97f"),
                            Active = true,
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 514, DateTimeKind.Local).AddTicks(2597),
                            Password = "10921321718522810424013620812023319215824350233",
                            PersonId = new Guid("3a7ecfe2-a437-4634-bb2d-d4e01f0d6ee8"),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DomainModels.General.MemberPermission", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDenied")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("MemberId");

                    b.HasIndex("PermissionId");

                    b.ToTable("MemberPermissions","General");
                });

            modelBuilder.Entity("DomainModels.General.Permission", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("ParentId");

                    b.ToTable("Permissions","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7280161e-bdfe-48d9-90fa-d3b8c80df47e"),
                            Action = "Index",
                            Active = true,
                            Controller = "Home",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 635, DateTimeKind.Local).AddTicks(8200),
                            Icon = "fa fa-home",
                            Order = 1,
                            Title = "صفحه اصلی سایت",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Action = "",
                            Active = true,
                            Controller = "",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 660, DateTimeKind.Local).AddTicks(7050),
                            Icon = "fa fa-address-book",
                            Order = 1,
                            ParentId = new Guid("7280161e-bdfe-48d9-90fa-d3b8c80df47e"),
                            Title = "اطلاعات پایه",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("e6ebe0b5-601a-4fcc-adba-0e30d861c2f4"),
                            Action = "",
                            Active = true,
                            Controller = "",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(1038),
                            Icon = "fa fa-server",
                            Order = 2,
                            ParentId = new Guid("7280161e-bdfe-48d9-90fa-d3b8c80df47e"),
                            Title = "سیستم",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Action = "Index",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(1250),
                            Icon = "fa fa-users",
                            Order = 1,
                            ParentId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Title = "تعریف نقش",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Action = "Index",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(1335),
                            Icon = "fa fa-user",
                            Order = 2,
                            ParentId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Title = "تعریف کاربر",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Action = "Index",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2258),
                            Icon = "fa fa-cogs",
                            Order = 3,
                            ParentId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Title = "سطح دسترسی",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("e7c93552-4e07-4d69-ba6a-baa5229c2278"),
                            Action = "_Create",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2389),
                            Icon = "fa fa-plus",
                            Order = 4,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "ثبت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("67323792-38c3-490b-ba31-eb87c1087ea6"),
                            Action = "_Update",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2464),
                            Icon = "fa fa-edit",
                            Order = 3,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "ویرایش",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("0c19f3a5-a90c-4760-968d-af6028fef21f"),
                            Action = "_Delete",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2547),
                            Icon = "fa fa-trash",
                            Order = 1,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "حذف",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("547e86be-132e-41f7-a8f3-73eb25bd755b"),
                            Action = "_List",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2625),
                            Icon = "fa fa-list",
                            Order = 2,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "اطلاعات",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("3a4b0912-7700-41cd-84ca-9986a6af982a"),
                            Action = "_Menu",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2700),
                            Icon = "fa fa-navicon",
                            Order = 1,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "منو",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("a05ecc96-0663-4fb2-aabd-18dede5a5cff"),
                            Action = "_Create",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2772),
                            Icon = "fa fa-plus",
                            Order = 2,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "ثبت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("ff298292-be77-43a0-ac99-d31f6c38c0bb"),
                            Action = "_Role",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2842),
                            Icon = "fa fa-users",
                            Order = 8,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "گروه کاربری",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("0da690bc-f675-4d8f-82f5-e6d4a5f82918"),
                            Action = "_Order",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2912),
                            Icon = "fa fa-list-ol",
                            Order = 6,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "اولویت بندی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("8c4994a2-a808-4c81-8086-ee501b2ac0fe"),
                            Action = "_Member",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(2987),
                            Icon = "fa fa-user",
                            Order = 7,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "کاربر",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("9e404679-1059-495e-aaec-9aa9371ed354"),
                            Action = "_Update",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3057),
                            Icon = "fa fa-edit",
                            Order = 4,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "ویرایش",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("b41312d1-cec1-4f3b-935f-5359bba15936"),
                            Action = "_List",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3177),
                            Icon = "fa fa-list",
                            Order = 5,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "اطلاعات",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("b9a02ea5-dd3f-48a8-831b-5f4154544f00"),
                            Action = "_Delete",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3256),
                            Icon = "fa fa-trash",
                            Order = 3,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "حذف",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("cb313af5-85ba-42b0-a263-6ae1549dc13b"),
                            Action = "ChangePeriority",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3332),
                            Icon = "fa fa-edit",
                            Order = 1,
                            ParentId = new Guid("0da690bc-f675-4d8f-82f5-e6d4a5f82918"),
                            Title = "تغییر اولویت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("0b56bebc-01ff-4619-bd45-4652fecef76e"),
                            Action = "SetRolePermission",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3404),
                            Icon = "fa fa-edit",
                            Order = 1,
                            ParentId = new Guid("ff298292-be77-43a0-ac99-d31f6c38c0bb"),
                            Title = "تخصیص دسترسی گروه",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("3c3f40b8-7399-41d5-a5ce-00c6e0ffb583"),
                            Action = "SetMemberPermission",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3475),
                            Icon = "fa fa-edit",
                            Order = 1,
                            ParentId = new Guid("8c4994a2-a808-4c81-8086-ee501b2ac0fe"),
                            Title = "تخصیص دسترسی کاربر",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("9009f178-1385-4fed-b0a7-abd5aee7a521"),
                            Action = "_Tree",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3547),
                            Icon = "fa fa-list-ul",
                            Order = 6,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "نمایش درختی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("d49cdafd-e0ae-46c1-ba80-d4a9b71f86a6"),
                            Action = "_Create",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3620),
                            Icon = "fa fa-plus",
                            Order = 1,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "ثبت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("15c526e5-879a-4a4a-84fb-06941ec9e78e"),
                            Action = "_Update",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3692),
                            Icon = "fa fa-edit",
                            Order = 2,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "ویرایش",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("07760487-9097-4431-b7b9-b6dbf9bd9416"),
                            Action = "_List",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3764),
                            Icon = "fa fa-list",
                            Order = 4,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "اطلاعات",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("643eef28-7e01-40d8-bfe7-4cd5c95c770e"),
                            Action = "_Delete",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3836),
                            Icon = "fa fa-trash",
                            Order = 3,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "حذف",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("4a6668fe-92ce-47e9-ac44-73312d71a602"),
                            Action = "_Permission",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(3907),
                            Icon = "fa fa-cogs",
                            Order = 7,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "دسترسی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("44683454-d0a3-48ee-bc83-fa18f6103e65"),
                            Action = "_Permission",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Local).AddTicks(4022),
                            Icon = "fa fa-cogs",
                            Order = 5,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "دسترسی",
                            Visible = false
                        });
                });

            modelBuilder.Entity("DomainModels.General.Person", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Persons","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a7ecfe2-a437-4634-bb2d-d4e01f0d6ee8"),
                            Birthday = new DateTime(1993, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 511, DateTimeKind.Local).AddTicks(1222),
                            Email = "Vahid031@yahoo.com",
                            FirstName = "وحید",
                            Gender = true,
                            LastName = "گودرزی",
                            MobileNumber = "09212681463",
                            NationalCode = "0310956196",
                            PhoneNumber = "02634558363"
                        });
                });

            modelBuilder.Entity("DomainModels.General.Role", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("ParentId");

                    b.ToTable("Roles","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 519, DateTimeKind.Local).AddTicks(3305),
                            Title = "Admin"
                        });
                });

            modelBuilder.Entity("DomainModels.General.RoleMember", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("MemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleMembers","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad7ff4cc-802d-443f-a35a-c9b086b4fe39"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 520, DateTimeKind.Local).AddTicks(9498),
                            MemberId = new Guid("4c1b92e9-d68b-4794-8f0f-293b67eed97f"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        });
                });

            modelBuilder.Entity("DomainModels.General.RolePermission", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4cce2b32-e16e-4ed0-97a9-d24cce60ef4b"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(6546),
                            PermissionId = new Guid("7280161e-bdfe-48d9-90fa-d3b8c80df47e"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("53d599d6-66b7-4754-a5e4-2c024a633172"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(7899),
                            PermissionId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("f50f3d99-f576-49ec-8d1a-00a113d147a0"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(7959),
                            PermissionId = new Guid("e6ebe0b5-601a-4fcc-adba-0e30d861c2f4"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("135251e8-2763-4f10-87d7-c73d990a3928"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(7986),
                            PermissionId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("5919fa34-41f9-4b32-8efd-f7e97988c6c1"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8018),
                            PermissionId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("d7c9d671-c888-4d25-9886-f9c3b91dacd7"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8046),
                            PermissionId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("610e8678-2904-48ba-a071-a1f6c08fc49b"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8071),
                            PermissionId = new Guid("e7c93552-4e07-4d69-ba6a-baa5229c2278"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("6d8eed21-8da6-4de0-813a-6d72afd12981"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8096),
                            PermissionId = new Guid("67323792-38c3-490b-ba31-eb87c1087ea6"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("4feb3228-0974-48d5-b51c-327d3a374913"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8120),
                            PermissionId = new Guid("0c19f3a5-a90c-4760-968d-af6028fef21f"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("f4b79fc6-86df-4095-b39c-edf23a410f98"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8145),
                            PermissionId = new Guid("547e86be-132e-41f7-a8f3-73eb25bd755b"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("9600fc1d-6814-4627-afc3-b833dc798f79"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8170),
                            PermissionId = new Guid("3a4b0912-7700-41cd-84ca-9986a6af982a"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("7b49b467-6eaf-4549-a050-9b0e0e8e2828"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8195),
                            PermissionId = new Guid("a05ecc96-0663-4fb2-aabd-18dede5a5cff"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("5ffcadbb-ad88-4d39-b135-6becb00f8307"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8221),
                            PermissionId = new Guid("ff298292-be77-43a0-ac99-d31f6c38c0bb"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("0aaab24c-cb5c-46a6-b31e-f69488de725c"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8245),
                            PermissionId = new Guid("0da690bc-f675-4d8f-82f5-e6d4a5f82918"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("fc020d52-8bc0-4571-ad54-a9e13a1f4b94"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8269),
                            PermissionId = new Guid("8c4994a2-a808-4c81-8086-ee501b2ac0fe"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("1f214385-7cbd-41d0-9b00-ed3ffd83ea8d"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8347),
                            PermissionId = new Guid("9e404679-1059-495e-aaec-9aa9371ed354"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("c0bb2eec-90f5-41ac-9a51-37f6f87bbfbf"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8373),
                            PermissionId = new Guid("b41312d1-cec1-4f3b-935f-5359bba15936"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("1a84dc3f-eb28-4aa2-a581-e33d33a531f8"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8399),
                            PermissionId = new Guid("b9a02ea5-dd3f-48a8-831b-5f4154544f00"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("f0379d8a-7be6-4922-a884-ebf02b935eee"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8424),
                            PermissionId = new Guid("cb313af5-85ba-42b0-a263-6ae1549dc13b"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("619c0a06-7a9f-49b3-8083-10b31c3f90f7"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8448),
                            PermissionId = new Guid("0b56bebc-01ff-4619-bd45-4652fecef76e"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("4f35dac0-0ed0-4f56-b78a-cdc6085a2061"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8474),
                            PermissionId = new Guid("3c3f40b8-7399-41d5-a5ce-00c6e0ffb583"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("6f1b49df-e2d8-42b1-9526-fea2587cd71e"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8497),
                            PermissionId = new Guid("9009f178-1385-4fed-b0a7-abd5aee7a521"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("4f9afa33-dbcb-4f7a-825a-de0b14336f77"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8521),
                            PermissionId = new Guid("d49cdafd-e0ae-46c1-ba80-d4a9b71f86a6"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("ceda1863-5096-406b-a69f-9d677632d730"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8545),
                            PermissionId = new Guid("15c526e5-879a-4a4a-84fb-06941ec9e78e"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("34234e9c-998b-4739-99ee-e46770d14915"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8568),
                            PermissionId = new Guid("07760487-9097-4431-b7b9-b6dbf9bd9416"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("882a9c4b-2756-4760-be4f-609802e76c93"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8592),
                            PermissionId = new Guid("643eef28-7e01-40d8-bfe7-4cd5c95c770e"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("f3900c04-d65a-4301-8b17-48e7d4679ac2"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8616),
                            PermissionId = new Guid("4a6668fe-92ce-47e9-ac44-73312d71a602"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        },
                        new
                        {
                            Id = new Guid("d1c36084-3998-4777-94ec-879bd9252597"),
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 662, DateTimeKind.Local).AddTicks(8640),
                            PermissionId = new Guid("44683454-d0a3-48ee-bc83-fa18f6103e65"),
                            RoleId = new Guid("6f2d54ec-f19e-487b-adbd-d4adf7e13be9")
                        });
                });

            modelBuilder.Entity("DomainModels.General.Log", b =>
                {
                    b.HasOne("DomainModels.General.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");
                });

            modelBuilder.Entity("DomainModels.General.LogDetail", b =>
                {
                    b.HasOne("DomainModels.General.Log", "Log")
                        .WithMany("LogDetails")
                        .HasForeignKey("LogId");
                });

            modelBuilder.Entity("DomainModels.General.Member", b =>
                {
                    b.HasOne("DomainModels.General.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("DomainModels.General.MemberPermission", b =>
                {
                    b.HasOne("DomainModels.General.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("DomainModels.General.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId");
                });

            modelBuilder.Entity("DomainModels.General.Permission", b =>
                {
                    b.HasOne("DomainModels.General.Permission", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("DomainModels.General.Role", b =>
                {
                    b.HasOne("DomainModels.General.Role", "RoleParent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("DomainModels.General.RoleMember", b =>
                {
                    b.HasOne("DomainModels.General.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("DomainModels.General.Role", "Role")
                        .WithMany("RoleMembers")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("DomainModels.General.RolePermission", b =>
                {
                    b.HasOne("DomainModels.General.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId");

                    b.HasOne("DomainModels.General.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
