// <auto-generated />
using System;
using DatabaseContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DatabaseContext.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class UnitOfWorkModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainModels.General.Log", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("State")
                        .HasColumnType("tinyint")
                        .HasMaxLength(10);

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("MemberId");

                    b.ToTable("Logs","General");
                });

            modelBuilder.Entity("DomainModels.General.LogDetail", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LogId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyName")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("PropertyValue")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("LogId");

                    b.ToTable("LogDetails","General");
                });

            modelBuilder.Entity("DomainModels.General.Member", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PersonId");

                    b.ToTable("Members","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c25129b9-07d6-42ca-91dd-756aefdced03"),
                            Active = true,
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 789, DateTimeKind.Local).AddTicks(9532),
                            Password = "10921321718522810424013620812023319215824350233",
                            PersonId = new Guid("a2dd8769-8830-48ed-963c-d06a47baa1d4"),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("DomainModels.General.MemberPermission", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsDenied")
                        .HasColumnType("bit");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("MemberId");

                    b.HasIndex("PermissionId");

                    b.ToTable("MemberPermissions","General");
                });

            modelBuilder.Entity("DomainModels.General.Permission", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<int?>("Order")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("ParentId");

                    b.ToTable("Permissions","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Action = "",
                            Active = true,
                            Controller = "",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 660, DateTimeKind.Unspecified).AddTicks(7050),
                            Icon = "fa fa-address-book",
                            Order = 1,
                            Title = "اطلاعات پایه",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("e6ebe0b5-601a-4fcc-adba-0e30d861c2f4"),
                            Action = "",
                            Active = true,
                            Controller = "",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(1038),
                            Icon = "fa fa-server",
                            Order = 2,
                            Title = "سیستم",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Action = "Index",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(1250),
                            Icon = "fa fa-users",
                            Order = 1,
                            ParentId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Title = "تعریف نقش",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Action = "Index",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(1335),
                            Icon = "fa fa-user",
                            Order = 2,
                            ParentId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Title = "تعریف کاربر",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Action = "Index",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2258),
                            Icon = "fa fa-cogs",
                            Order = 3,
                            ParentId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            Title = "سطح دسترسی",
                            Visible = true
                        },
                        new
                        {
                            Id = new Guid("e7c93552-4e07-4d69-ba6a-baa5229c2278"),
                            Action = "_Create",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2389),
                            Icon = "fa fa-plus",
                            Order = 4,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "ثبت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("67323792-38c3-490b-ba31-eb87c1087ea6"),
                            Action = "_Update",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2464),
                            Icon = "fa fa-edit",
                            Order = 3,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "ویرایش",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("0c19f3a5-a90c-4760-968d-af6028fef21f"),
                            Action = "_Delete",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2547),
                            Icon = "fa fa-trash",
                            Order = 1,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "حذف",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("547e86be-132e-41f7-a8f3-73eb25bd755b"),
                            Action = "_List",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2625),
                            Icon = "fa fa-list",
                            Order = 2,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "اطلاعات",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("3a4b0912-7700-41cd-84ca-9986a6af982a"),
                            Action = "_Menu",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2700),
                            Icon = "fa fa-navicon",
                            Order = 1,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "منو",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("a05ecc96-0663-4fb2-aabd-18dede5a5cff"),
                            Action = "_Create",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2772),
                            Icon = "fa fa-plus",
                            Order = 2,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "ثبت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("ff298292-be77-43a0-ac99-d31f6c38c0bb"),
                            Action = "_Role",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2842),
                            Icon = "fa fa-users",
                            Order = 8,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "گروه کاربری",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("0da690bc-f675-4d8f-82f5-e6d4a5f82918"),
                            Action = "_Order",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2912),
                            Icon = "fa fa-list-ol",
                            Order = 6,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "اولویت بندی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("8c4994a2-a808-4c81-8086-ee501b2ac0fe"),
                            Action = "_Member",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(2987),
                            Icon = "fa fa-user",
                            Order = 7,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "کاربر",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("9e404679-1059-495e-aaec-9aa9371ed354"),
                            Action = "_Update",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3057),
                            Icon = "fa fa-edit",
                            Order = 4,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "ویرایش",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("b41312d1-cec1-4f3b-935f-5359bba15936"),
                            Action = "_List",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3177),
                            Icon = "fa fa-list",
                            Order = 5,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "اطلاعات",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("b9a02ea5-dd3f-48a8-831b-5f4154544f00"),
                            Action = "_Delete",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3256),
                            Icon = "fa fa-trash",
                            Order = 3,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "حذف",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("cb313af5-85ba-42b0-a263-6ae1549dc13b"),
                            Action = "ChangePeriority",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3332),
                            Icon = "fa fa-edit",
                            Order = 1,
                            ParentId = new Guid("0da690bc-f675-4d8f-82f5-e6d4a5f82918"),
                            Title = "تغییر اولویت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("0b56bebc-01ff-4619-bd45-4652fecef76e"),
                            Action = "SetRolePermission",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3404),
                            Icon = "fa fa-edit",
                            Order = 1,
                            ParentId = new Guid("ff298292-be77-43a0-ac99-d31f6c38c0bb"),
                            Title = "تخصیص دسترسی گروه",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("3c3f40b8-7399-41d5-a5ce-00c6e0ffb583"),
                            Action = "SetMemberPermission",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3475),
                            Icon = "fa fa-edit",
                            Order = 1,
                            ParentId = new Guid("8c4994a2-a808-4c81-8086-ee501b2ac0fe"),
                            Title = "تخصیص دسترسی کاربر",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("9009f178-1385-4fed-b0a7-abd5aee7a521"),
                            Action = "_Tree",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3547),
                            Icon = "fa fa-list-ul",
                            Order = 6,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "نمایش درختی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("d49cdafd-e0ae-46c1-ba80-d4a9b71f86a6"),
                            Action = "_Create",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3620),
                            Icon = "fa fa-plus",
                            Order = 1,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "ثبت",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("15c526e5-879a-4a4a-84fb-06941ec9e78e"),
                            Action = "_Update",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3692),
                            Icon = "fa fa-edit",
                            Order = 2,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "ویرایش",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("07760487-9097-4431-b7b9-b6dbf9bd9416"),
                            Action = "_List",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3764),
                            Icon = "fa fa-list",
                            Order = 4,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "اطلاعات",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("643eef28-7e01-40d8-bfe7-4cd5c95c770e"),
                            Action = "_Delete",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3836),
                            Icon = "fa fa-trash",
                            Order = 3,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "حذف",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("4a6668fe-92ce-47e9-ac44-73312d71a602"),
                            Action = "_Permission",
                            Active = true,
                            Controller = "Role",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(3907),
                            Icon = "fa fa-cogs",
                            Order = 7,
                            ParentId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            Title = "دسترسی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("44683454-d0a3-48ee-bc83-fa18f6103e65"),
                            Action = "_Permission",
                            Active = true,
                            Controller = "Member",
                            CreateDate = new DateTime(2021, 1, 29, 22, 58, 48, 661, DateTimeKind.Unspecified).AddTicks(4022),
                            Icon = "fa fa-cogs",
                            Order = 5,
                            ParentId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            Title = "دسترسی",
                            Visible = false
                        },
                        new
                        {
                            Id = new Guid("fc5a8eae-9287-4efc-91de-9d1c47e19aa6"),
                            Action = "_Tree",
                            Active = true,
                            Controller = "Permission",
                            CreateDate = new DateTime(2021, 2, 4, 22, 25, 6, 390, DateTimeKind.Unspecified),
                            Icon = "fa fa-list-ul",
                            Order = 10,
                            ParentId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            Title = "نمایش درختی",
                            Visible = false
                        });
                });

            modelBuilder.Entity("DomainModels.General.Person", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<bool?>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25);

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(11)")
                        .HasMaxLength(11);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.ToTable("Persons","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a2dd8769-8830-48ed-963c-d06a47baa1d4"),
                            Birthday = new DateTime(1993, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 786, DateTimeKind.Local).AddTicks(7487),
                            Email = "Vahid031@yahoo.com",
                            FirstName = "وحید",
                            Gender = true,
                            LastName = "گودرزی",
                            MobileNumber = "09212681463",
                            NationalCode = "0310956196",
                            PhoneNumber = "02634558363"
                        });
                });

            modelBuilder.Entity("DomainModels.General.Role", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("ParentId");

                    b.ToTable("Roles","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 794, DateTimeKind.Local).AddTicks(7678),
                            Title = "Admin"
                        });
                });

            modelBuilder.Entity("DomainModels.General.RoleMember", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("MemberId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleMembers","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("680e3c93-26c8-41d1-84a5-19ac0dff9d40"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 796, DateTimeKind.Local).AddTicks(3804),
                            MemberId = new Guid("c25129b9-07d6-42ca-91dd-756aefdced03"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        });
                });

            modelBuilder.Entity("DomainModels.General.RolePermission", b =>
                {
                    b.Property<Guid?>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Clustered", false);

                    b.HasIndex("CreateDate")
                        .IsUnique()
                        .HasAnnotation("SqlServer:Clustered", true);

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions","General");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fdac15ae-5100-420b-aa77-a9b9002c233b"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(4722),
                            PermissionId = new Guid("2164228a-2df8-4a6b-9a36-eee99bcd2cb6"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("448d2c00-6b26-4fc6-8be3-c79235c69a77"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6107),
                            PermissionId = new Guid("e6ebe0b5-601a-4fcc-adba-0e30d861c2f4"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("edee7f40-5398-4e68-9885-c1f0c91dd63a"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6167),
                            PermissionId = new Guid("9555bc99-4c77-4307-aa6e-30f2074def17"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("c2cecf02-043d-4bf7-a259-83115191460b"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6193),
                            PermissionId = new Guid("5f11abf0-8e5c-4b95-bc56-db6d5581c423"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("fbaa0e07-bb13-4daa-a5f8-605119b7c273"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6219),
                            PermissionId = new Guid("8aa921c5-0e6f-4e35-b80a-5d76065ac615"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("f85e0c94-8f29-4ad9-a427-3a7c004e4cd6"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6245),
                            PermissionId = new Guid("e7c93552-4e07-4d69-ba6a-baa5229c2278"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("83c4fee5-b74d-49f9-9521-474e938f8aac"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6267),
                            PermissionId = new Guid("67323792-38c3-490b-ba31-eb87c1087ea6"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("6fb93b72-cbde-4a17-becb-04499cfd196a"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6291),
                            PermissionId = new Guid("0c19f3a5-a90c-4760-968d-af6028fef21f"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("944a877a-d3ca-4029-b941-f8b16c4cd6f8"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6321),
                            PermissionId = new Guid("547e86be-132e-41f7-a8f3-73eb25bd755b"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("d49f6d65-39b5-468c-bb9a-6b9fa8afe552"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6346),
                            PermissionId = new Guid("3a4b0912-7700-41cd-84ca-9986a6af982a"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("569fc3c6-7d37-4d4b-b67d-07820608faa3"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6370),
                            PermissionId = new Guid("a05ecc96-0663-4fb2-aabd-18dede5a5cff"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("b4f5e44e-e62b-4f77-8c88-fdabd5aafb03"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6393),
                            PermissionId = new Guid("ff298292-be77-43a0-ac99-d31f6c38c0bb"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("61d5a39e-bbfc-4ac3-b025-892e7d6115d8"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6416),
                            PermissionId = new Guid("0da690bc-f675-4d8f-82f5-e6d4a5f82918"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("73eae3c9-e4c1-4294-96a5-ad22a4f1a5f5"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6439),
                            PermissionId = new Guid("8c4994a2-a808-4c81-8086-ee501b2ac0fe"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("27b4f154-d587-4940-89de-83b1cac8f7a8"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6462),
                            PermissionId = new Guid("9e404679-1059-495e-aaec-9aa9371ed354"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("f6757ba4-56da-488f-9dfa-91bce4fddc73"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6485),
                            PermissionId = new Guid("b41312d1-cec1-4f3b-935f-5359bba15936"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("8d1f1d16-98b8-48fc-86f9-235f54d96399"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6510),
                            PermissionId = new Guid("b9a02ea5-dd3f-48a8-831b-5f4154544f00"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("19ab5988-88db-43f3-84ff-2ca5a649b317"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6535),
                            PermissionId = new Guid("cb313af5-85ba-42b0-a263-6ae1549dc13b"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("65b3bbd3-21f7-45af-9e08-26c0417a427c"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6597),
                            PermissionId = new Guid("0b56bebc-01ff-4619-bd45-4652fecef76e"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("3dd8835e-9284-44a5-824f-6a9bac54d4bd"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6624),
                            PermissionId = new Guid("3c3f40b8-7399-41d5-a5ce-00c6e0ffb583"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("8b04925f-d5dc-4b04-abcc-61c84c460b2e"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6647),
                            PermissionId = new Guid("9009f178-1385-4fed-b0a7-abd5aee7a521"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("d7ececdd-10b1-4a6d-ac47-c4d3073ae1bf"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6671),
                            PermissionId = new Guid("d49cdafd-e0ae-46c1-ba80-d4a9b71f86a6"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("9497d078-c5c4-48f3-b389-e900aec5df56"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6694),
                            PermissionId = new Guid("15c526e5-879a-4a4a-84fb-06941ec9e78e"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("80e308c5-286c-4ace-ae67-8c999a1a0b64"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6717),
                            PermissionId = new Guid("07760487-9097-4431-b7b9-b6dbf9bd9416"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("8bbc66a0-dbc3-40f7-a5b9-c73537ce1de5"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6742),
                            PermissionId = new Guid("643eef28-7e01-40d8-bfe7-4cd5c95c770e"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("42ab6030-fa62-47ec-a107-3d999be98778"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6766),
                            PermissionId = new Guid("4a6668fe-92ce-47e9-ac44-73312d71a602"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("b85ef976-a3be-425f-9dda-b9a9b1fbfb1e"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6789),
                            PermissionId = new Guid("44683454-d0a3-48ee-bc83-fa18f6103e65"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        },
                        new
                        {
                            Id = new Guid("fe37f838-dda3-49fb-abf6-c5dc186b8bf4"),
                            CreateDate = new DateTime(2021, 2, 4, 22, 56, 48, 898, DateTimeKind.Local).AddTicks(6811),
                            PermissionId = new Guid("fc5a8eae-9287-4efc-91de-9d1c47e19aa6"),
                            RoleId = new Guid("3e232441-90f0-422b-92e2-e4d91700eaa8")
                        });
                });

            modelBuilder.Entity("DomainModels.General.Log", b =>
                {
                    b.HasOne("DomainModels.General.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");
                });

            modelBuilder.Entity("DomainModels.General.LogDetail", b =>
                {
                    b.HasOne("DomainModels.General.Log", "Log")
                        .WithMany("LogDetails")
                        .HasForeignKey("LogId");
                });

            modelBuilder.Entity("DomainModels.General.Member", b =>
                {
                    b.HasOne("DomainModels.General.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("DomainModels.General.MemberPermission", b =>
                {
                    b.HasOne("DomainModels.General.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("DomainModels.General.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId");
                });

            modelBuilder.Entity("DomainModels.General.Permission", b =>
                {
                    b.HasOne("DomainModels.General.Permission", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("DomainModels.General.Role", b =>
                {
                    b.HasOne("DomainModels.General.Role", "RoleParent")
                        .WithMany()
                        .HasForeignKey("ParentId");
                });

            modelBuilder.Entity("DomainModels.General.RoleMember", b =>
                {
                    b.HasOne("DomainModels.General.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId");

                    b.HasOne("DomainModels.General.Role", "Role")
                        .WithMany("RoleMembers")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("DomainModels.General.RolePermission", b =>
                {
                    b.HasOne("DomainModels.General.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId");

                    b.HasOne("DomainModels.General.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId");
                });
#pragma warning restore 612, 618
        }
    }
}
